import './globals.css'
import { Nunito_Sans } from 'next/font/google';
import MainLayout from '@/shared/components/layouts/MainLayout';

const nunito = Nunito_Sans({subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={`text-slate-600 ${nunito.className} text-secondary`}>
        <MainLayout>
          {children}
        </MainLayout>
      </body>
    </html>
  )
}
